### ISSUE TITLE
Make an universal solution (not only for golang)

### ISSUE THREAD

**Issue by ariary** [doyensec/safeurl#2]
Hi!

More a question/proposition than  an issue:

Like it has been said by a Reddit user on a post sharing the library (I can’t retrieve the link sorry), it could have been a great thing to have a solution not « language dependent ».

One idea to do that is to set up a proxy (with the logic of `safeurl`) and then force the client to use the proxy to perform requests. AFAIK it is possible to do it with many languages (go, python, etc)

So do you see (or have seen) any drawback or limitation with this approach ?

**Comment by v1ktor0t** [comment]
Hey @ariary, thank you for commenting.

The main goal of our implementation of `safeurl` was to provide a developer oriented/language specific way of mitigating SSRF vulnerabilities. The main idea is to provide an easy-to-integrate tool, which will allow developers to produce secure features, without needing to off-load that work to other teams and rely on external security controls.

As for network level protections, solutions such as [smokescreen](https://github.com/stripe/smokescreen) exist, which work as you described. 

Ultimately, like everything security, a defense-in-depth approach is recommended. There is no practical reason which would not allow you to have both language and network level SSRF mitigations.
